### ISSUE TITLE
Application notes

### ISSUE THREAD

**Issue by rinigus** [poetaster/keypeer.org#8]
Looking at the current text of the application and conditions (https://nlnet.nl/entrust/eligibility/):

In the text, we have to highlight and relate our aims to the eligible activities. The ones that I found:
- design and development of open source software and open hardware
- software engineering aimed at adapting to new usage areas or improving software quality (we aim at new usage area)
- understanding user requirements and improving usability/inclusive design

Some other aspects that should be stressed in the application: NGI0 Entrust is designed to move beyond the status quo and create a virtuous cycle of innovation through free and open source software, libre hardware and open standards. 

In general, we should be fitting it well.

Regarding text and its parts.

Abstract has to be written from scratch. Its 1200 chars

Re budget: I think we should factor in also 
- discussions with service providers and design of possible APIs. it just takes time on all sides to align with a common goals
- legal advice on mechanisms allowing to make such service as cheap as possible. for example, do donations qualify?
- discussion and finding cost processor, api with it

Challenges:

I wouldn't state that "The most challenging technical aspect will be probably be homomorphic cryptography of the user / key store". If I would be evaluating the application this would suggest that the applicants want to play with this part as much as they can and not the rest of the project. Which is wrong and we should tone that down to avoid it. We can mention it as "other challenges" and keep the reference.

Otherwise, we expect that there will be many smaller and solvable challenges. Probably the main is to make it all work together and assist app writers to integrate it into the apps.

Ecosystem:

regarding pure maps: which will be used for testing a number of API's for accessing map data, such as MapTiler and Stadia, concurrently.

As soon as the first stage is ready, we will engage with the other mapping applications (Gnome Maps, uNav, and others). We will promote this new opportunity in relevant mobile and desktop linux and other FOSS communities. 

Some unrelated:

Many consider API keys relevant to online services. But also offline data (such as maps) has to be somehow generated and distributed. Which, in principle, could also be a service that would request API keys for downloading maps.

**Comment by poetaster** [comment]
> Abstract has to be written from scratch. Its 1200 chars

The introduction doc, till now, is 931 words +- 

I've worked all these observations, more or less into the document and embedded the introduction too. Let's see if we get some feedback from the Sailmates.

**Comment by rinigus** [comment]
Abstract should be shorter, see the form

**Comment by rinigus** [comment]
Closing as addressed
